export const caseStudies = [
  {
    id: "001",
    name: "Satellite",
    year: "2023",
    description: `Implement use of web workers to provide extra thread for etc`,
    githubLink: "somelink",
  },
  {
    id: "002",
    name: "Scrape",
    year: "2023",
    description: `Experiment with puppeteer to scrape data from sites and harvest it`,
    githubLink: "somelink",
  },
  {
    id: "003",
    name: "Shaders experiment",
    year: "2023",
    description: `Implement custom shaders for a better user experience`,
    githubLink: "somelink",
  },
  {
    id: "004",
    name: "Satellite",
    year: "2023",
    description: `Implement use of web workers to provide extra thread for etc`,
    githubLink: "somelink",
  },
  {
    id: "005",
    name: "Scrape",
    year: "2023",
    description: `Experiment with puppeteer to scrape data from sites and harvest it`,
    githubLink: "somelink",
  },
  {
    id: "006",
    name: "Shaders experiment",
    year: "2023",
    description: `Implement custom shaders for a better user experience`,
    githubLink: "somelink",
  },
  {
    id: "007",
    name: "Shaders experiment",
    year: "2023",
    description: `Implement custom shaders for a better user experience`,
    githubLink: "somelink",
  },
  {
    id: "008",
    name: "Satellite",
    year: "2023",
    description: `Implement use of web workers to provide extra thread for etc`,
    githubLink: "somelink",
  },
  {
    id: "009",
    name: "Scrape",
    year: "2023",
    description: `Experiment with puppeteer to scrape data from sites and harvest it`,
    githubLink: "somelink",
  },
  {
    id: "010",
    name: "Shaders experiment",
    year: "2023",
    description: `Implement custom shaders for a better user experience`,
    githubLink: "somelink",
  },
];
